name: orbit_agent

services:
  orbit-typesense:
    image: typesense/typesense:26.0
    container_name: orbit-typesense
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense/dbdata:/data
    command: '--data-dir /data --api-key=kai_typesense --enable-cors'
    env_file:
      - .env.kai

  orbit-text2sql-agent:
    image: ghcr.io/mta-tech/kai:latest
    container_name: orbit-text2sql-agent
    hostname: orbit-text2sql-agent
    restart: on-failure
    ports:
      - "8005:8005"
    depends_on:
      - orbit-typesense
    environment:
      - TYPESENSE_HOST=orbit-typesense
    env_file:
      - .env.kai
    networks:
      - default

  orbit-worker:
    image: ghcr.io/mta-tech/java-orbit-worker:latest
    container_name: orbit-worker
    restart: on-failure
    depends_on:
      - orbit-text2sql-agent
    env_file:
      - .env.orbit
  orbit-redis:
    image: redis:7-alpine
    container_name: orbit-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]

networks:
  default:
    external: true
    name: agentic_network